all_positions = [
    {'square': 0, 'index': 0},
    {'square': 0, 'index': 1},
    {'square': 0, 'index': 2},
    {'square': 0, 'index': 3},
    {'square': 0, 'index': 4},
    {'square': 0, 'index': 5},
    {'square': 0, 'index': 6},
    {'square': 0, 'index': 7},
    {'square': 1, 'index': 0},
    {'square': 1, 'index': 1},
    {'square': 1, 'index': 2},
    {'square': 1, 'index': 3},
    {'square': 1, 'index': 4},
    {'square': 1, 'index': 5},
    {'square': 1, 'index': 6},
    {'square': 1, 'index': 7},
    {'square': 2, 'index': 0},
    {'square': 2, 'index': 1},
    {'square': 2, 'index': 2},
    {'square': 2, 'index': 3},
    {'square': 2, 'index': 4},
    {'square': 2, 'index': 5},
    {'square': 2, 'index': 6},
    {'square': 2, 'index': 7}
]
